### ISSUE TITLE
sys-apps/corenetwork-1.5.1 index.rst does not exist

### ISSUE THREAD

**Issue by DDtoma** [funtoo/corenetwork#1]
> > > Emerging (1 of 1) sys-apps/corenetwork-1.5.1::gentoo
> > > - corenetwork-1.5.1.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                              [ ok ]
> > >   Unpacking source...
> > >   Unpacking corenetwork-1.5.1.tar.gz to /var/tmp/portage/sys-apps/corenetwork-1.5.1/work
> > >   Source unpacked in /var/tmp/portage/sys-apps/corenetwork-1.5.1/work
> > >   Preparing source in /var/tmp/portage/sys-apps/corenetwork-1.5.1/work/corenetwork-1.5.1 ...
> > >   Source prepared.
> > >   Configuring source in /var/tmp/portage/sys-apps/corenetwork-1.5.1/work/corenetwork-1.5.1 ...
> > >   Source configured.
> > >   Compiling source in /var/tmp/portage/sys-apps/corenetwork-1.5.1/work/corenetwork-1.5.1 ...
> > >   Source compiled.
> > >   Test phase [not enabled]: sys-apps/corenetwork-1.5.1
> > > 
> > > Install corenetwork-1.5.1 into /var/tmp/portage/sys-apps/corenetwork-1.5.1/image/ category sys-apps
> > > /usr/bin/install: cannot stat ‘docs/index.rst’: No such file or directory
> > > !!! dodoc: docs/index.rst does not exist
> > > - ERROR: sys-apps/corenetwork-1.5.1::gentoo failed (install phase):
> > > -   dodoc failed
> > > - 
> > > - If you need support, post the output of `emerge --info '=sys-apps/corenetwork-1.5.1::gentoo'`,
> > > - the complete build log and the output of `emerge -pqv '=sys-apps/corenetwork-1.5.1::gentoo'`.
> > > - The complete build log is located at '/var/tmp/portage/sys-apps/corenetwork-1.5.1/temp/build.log'.
> > > - The ebuild environment file is located at '/var/tmp/portage/sys-apps/corenetwork-1.5.1/temp/environment'.
> > > - Working directory: '/var/tmp/portage/sys-apps/corenetwork-1.5.1/work/corenetwork-1.5.1'
> > > - S: '/var/tmp/portage/sys-apps/corenetwork-1.5.1/work/corenetwork-1.5.1'
> > > - QA Notice: file does not exist:
> > > - 
> > > -      dodoc: docs/index.rst does not exist
> > >   how to solve this bug?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2858

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
